from __future__ import annotations

from typing import Any

from holocron.platform.bronze import (
    coerce_boolish_uint8,
    coerce_float,
    coerce_int,
    iso_datetime_or_default,
)
from holocron.platform.raw_files import string_value
from holocron.sources.dld_open_data_bronze import (
    build_open_data_bronze_loader,
    dld_envelope_tuple,
    dld_row_key,
)

_SOURCE_NAME = "dld_od_transactions"
_COLUMNS = (
    "row_key",
    "run_id",
    "scraped_at",
    "mode",
    "date_window_start",
    "date_window_end",
    "page_index",
    "row_index",
    "transaction_number",
    "instance_date",
    "group_id",
    "group_en",
    "group_ar",
    "procedure_id",
    "procedure_en",
    "procedure_ar",
    "procedure_area",
    "actual_area",
    "trans_value",
    "total_buyer",
    "total_seller",
    "property_id",
    "property_type_id",
    "prop_type_en",
    "prop_type_ar",
    "property_sub_type_id",
    "prop_sb_type_en",
    "prop_sb_type_ar",
    "usage_id",
    "usage_en",
    "usage_ar",
    "rooms_en",
    "rooms_ar",
    "parking",
    "building_age",
    "parcel_id",
    "area_id",
    "area_en",
    "area_ar",
    "project_en",
    "project_ar",
    "master_project_en",
    "master_project_ar",
    "is_free_hold",
    "is_free_hold_en",
    "is_free_hold_ar",
    "is_offplan",
    "is_offplan_en",
    "is_offplan_ar",
    "nearest_metro_en",
    "nearest_metro_ar",
    "nearest_mall_en",
    "nearest_mall_ar",
    "nearest_landmark_en",
    "nearest_landmark_ar",
)


def _row_tuple(raw_row: dict[str, Any], *, fallback_run_id: str) -> tuple:
    row_key = dld_row_key(raw_row)
    d = raw_row.get("raw") or {}
    return (
        *dld_envelope_tuple(raw_row, row_key=row_key, fallback_run_id=fallback_run_id),
        string_value(d.get("TRANSACTION_NUMBER")),
        iso_datetime_or_default(d.get("INSTANCE_DATE")),
        coerce_int(d.get("GROUP_ID")),
        string_value(d.get("GROUP_EN")),
        string_value(d.get("GROUP_AR")),
        coerce_int(d.get("PROCEDURE_ID")),
        string_value(d.get("PROCEDURE_EN")),
        string_value(d.get("PROCEDURE_AR")),
        coerce_float(d.get("PROCEDURE_AREA")),
        coerce_float(d.get("ACTUAL_AREA")),
        coerce_int(d.get("TRANS_VALUE")),
        coerce_int(d.get("TOTAL_BUYER")),
        coerce_int(d.get("TOTAL_SELLER")),
        coerce_int(d.get("PROPERTY_ID")),
        coerce_int(d.get("PROPERTY_TYPE_ID")),
        string_value(d.get("PROP_TYPE_EN")),
        string_value(d.get("PROP_TYPE_AR")),
        coerce_int(d.get("PROPERTY_SUB_TYPE_ID")),
        string_value(d.get("PROP_SB_TYPE_EN")),
        string_value(d.get("PROP_SB_TYPE_AR")),
        coerce_int(d.get("USAGE_ID")),
        string_value(d.get("USAGE_EN")),
        string_value(d.get("USAGE_AR")),
        string_value(d.get("ROOMS_EN")),
        string_value(d.get("ROOMS_AR")),
        string_value(d.get("PARKING")),
        coerce_int(d.get("BUILDING_AGE")),
        string_value(d.get("PARCEL_ID")),
        coerce_int(d.get("AREA_ID")),
        string_value(d.get("AREA_EN")),
        string_value(d.get("AREA_AR")),
        string_value(d.get("PROJECT_EN")),
        string_value(d.get("PROJECT_AR")),
        string_value(d.get("MASTER_PROJECT_EN")),
        string_value(d.get("MASTER_PROJECT_AR")),
        coerce_boolish_uint8(d.get("IS_FREE_HOLD")),
        string_value(d.get("IS_FREE_HOLD_EN")),
        string_value(d.get("IS_FREE_HOLD_AR")),
        coerce_boolish_uint8(d.get("IS_OFFPLAN")),
        string_value(d.get("IS_OFFPLAN_EN")),
        string_value(d.get("IS_OFFPLAN_AR")),
        string_value(d.get("NEAREST_METRO_EN")),
        string_value(d.get("NEAREST_METRO_AR")),
        string_value(d.get("NEAREST_MALL_EN")),
        string_value(d.get("NEAREST_MALL_AR")),
        string_value(d.get("NEAREST_LANDMARK_EN")),
        string_value(d.get("NEAREST_LANDMARK_AR")),
    )


load_release_to_clickhouse = build_open_data_bronze_loader(
    source_name=_SOURCE_NAME,
    column_names=_COLUMNS,
    row_builder=_row_tuple,
    replace_date_column="instance_date",
)
