"""ground CRM inbound workflow in observed and confirmed evidence

Revision ID: f2b8d0e4a6c1
Revises: e1a7c9d3f5b2
Create Date: 2026-08-04 14:00:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "f2b8d0e4a6c1"
down_revision: Union[str, Sequence[str], None] = "e1a7c9d3f5b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    string = sqlmodel.sql.sqltypes.AutoString
    op.add_column(
        "crm_inbound_enquiries",
        sa.Column("record_kind", string(), nullable=False, server_default="unqualified_contact"),
    )
    for name in ("observed_data", "inferred_data", "confirmed_data", "qualification"):
        op.add_column(
            "crm_inbound_enquiries",
            sa.Column(name, sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")),
        )
    op.add_column(
        "crm_inbound_enquiries", sa.Column("first_response_due_at", sa.DateTime(timezone=True))
    )
    op.add_column(
        "crm_inbound_enquiries", sa.Column("first_contact_at", sa.DateTime(timezone=True))
    )
    op.add_column(
        "crm_inbound_enquiries", sa.Column("last_contact_at", sa.DateTime(timezone=True))
    )
    op.add_column(
        "crm_inbound_enquiries",
        sa.Column("contact_attempt_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column("crm_inbound_enquiries", sa.Column("lost_reason", string()))
    op.create_index(
        op.f("ix_crm_inbound_enquiries_record_kind"),
        "crm_inbound_enquiries",
        ["record_kind"],
    )

    op.add_column(
        "crm_inbound_matches",
        sa.Column("fit", string(), nullable=False, server_default="review"),
    )
    op.add_column(
        "crm_inbound_matches",
        sa.Column("missing_fields", sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.create_index(op.f("ix_crm_inbound_matches_fit"), "crm_inbound_matches", ["fit"])

    op.create_table(
        "crm_inbound_activities",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("enquiry_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", string(), nullable=False),
        sa.Column("user_id", string(), nullable=False),
        sa.Column("activity_type", string(), nullable=False),
        sa.Column("body", sa.Text()),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["enquiry_id"], ["crm_inbound_enquiries.id"], ondelete="CASCADE"
        ),
    )
    for column in ("enquiry_id", "organization_id", "user_id", "activity_type"):
        op.create_index(
            op.f(f"ix_crm_inbound_activities_{column}"),
            "crm_inbound_activities",
            [column],
        )

    # Existing rows were generated by the former heuristic classifier. Keep them
    # visible for review, but do not treat those classifications as confirmed intent.
    op.execute(
        """
        UPDATE crm_inbound_enquiries
        SET intent = 'unknown',
            record_kind = 'unqualified_contact',
            status = 'needs_review',
            inferred_data = json_build_object(
                'legacy_intent', intent,
                'migration_note', 'Legacy heuristic classification requires confirmation'
            ),
            first_response_due_at = enquiry_date + interval '5 minutes'
        """
    )


def downgrade() -> None:
    op.drop_table("crm_inbound_activities")
    op.drop_index(op.f("ix_crm_inbound_matches_fit"), table_name="crm_inbound_matches")
    op.drop_column("crm_inbound_matches", "missing_fields")
    op.drop_column("crm_inbound_matches", "fit")
    op.drop_index(op.f("ix_crm_inbound_enquiries_record_kind"), table_name="crm_inbound_enquiries")
    for name in (
        "lost_reason",
        "contact_attempt_count",
        "last_contact_at",
        "first_contact_at",
        "first_response_due_at",
        "qualification",
        "confirmed_data",
        "inferred_data",
        "observed_data",
        "record_kind",
    ):
        op.drop_column("crm_inbound_enquiries", name)
