from __future__ import annotations

from typing import Any

from holocron.platform.bronze import (
    coerce_boolish_uint8,
    coerce_float,
    coerce_int,
    iso_datetime_or_default,
)
from holocron.platform.raw_files import string_value
from holocron.sources.dld_open_data_bronze import (
    build_open_data_bronze_loader,
    dld_envelope_tuple,
    dld_row_key,
)

_SOURCE_NAME = "dld_od_buildings"
_COLUMNS = (
    "row_key",
    "run_id",
    "scraped_at",
    "mode",
    "date_window_start",
    "date_window_end",
    "page_index",
    "row_index",
    "building_number",
    "parent_property_id",
    "parcel_id",
    "creation_date",
    "land_number",
    "land_sub_number",
    "land_type_id",
    "land_type_en",
    "land_type_ar",
    "prop_sub_type_id",
    "prop_sub_type_en",
    "prop_sub_type_ar",
    "actual_area",
    "built_up_area",
    "common_area",
    "actual_common_area",
    "floors",
    "bld_levels",
    "flats",
    "rooms",
    "rooms_en",
    "rooms_ar",
    "offices",
    "shops",
    "car_parks",
    "elevators",
    "swimming_pools",
    "is_free_hold",
    "is_free_hold_en",
    "is_free_hold_ar",
    "is_lease_hold",
    "is_lease_hold_en",
    "is_lease_hold_ar",
    "is_offplan_en",
    "is_offplan_ar",
    "is_registered",
    "pre_registration_number",
    "area_id",
    "area_en",
    "area_ar",
    "zone_id",
    "zone_en",
    "zone_ar",
    "master_project_id",
    "master_project_en",
    "master_project_ar",
    "project_number",
    "project_en",
    "project_ar",
)


def _row_tuple(raw_row: dict[str, Any], *, fallback_run_id: str) -> tuple:
    row_key = dld_row_key(raw_row)
    d = raw_row.get("raw") or {}
    return (
        *dld_envelope_tuple(raw_row, row_key=row_key, fallback_run_id=fallback_run_id),
        string_value(d.get("BUILDING_NUMBER")),
        coerce_int(d.get("PARENT_PROPERTY_ID")),
        string_value(d.get("PARCEL_ID")),
        iso_datetime_or_default(d.get("CREATION_DATE")),
        string_value(d.get("LAND_NUMBER")),
        coerce_int(d.get("LAND_SUB_NUMBER")),
        coerce_int(d.get("LAND_TYPE_ID")),
        string_value(d.get("LAND_TYPE_EN")),
        string_value(d.get("LAND_TYPE_AR")),
        coerce_int(d.get("PROP_SUB_TYPE_ID")),
        string_value(d.get("PROP_SUB_TYPE_EN")),
        string_value(d.get("PROP_SUB_TYPE_AR")),
        coerce_float(d.get("ACTUAL_AREA")),
        coerce_float(d.get("BUILT_UP_AREA")),
        coerce_float(d.get("COMMON_AREA")),
        coerce_float(d.get("ACTUAL_COMMON_AREA")),
        coerce_int(d.get("FLOORS")),
        coerce_int(d.get("BLD_LEVELS")),
        coerce_int(d.get("FLATS")),
        coerce_int(d.get("ROOMS")),
        string_value(d.get("ROOMS_EN")),
        string_value(d.get("ROOMS_AR")),
        coerce_int(d.get("OFFICES")),
        coerce_int(d.get("SHOPS")),
        coerce_int(d.get("CAR_PARKS")),
        coerce_int(d.get("ELEVATORS")),
        coerce_int(d.get("SWIMMING_POOLS")),
        coerce_boolish_uint8(d.get("IS_FREE_HOLD")),
        string_value(d.get("IS_FREE_HOLD_EN")),
        string_value(d.get("IS_FREE_HOLD_AR")),
        coerce_boolish_uint8(d.get("IS_LEASE_HOLD")),
        string_value(d.get("IS_LEASE_HOLD_EN")),
        string_value(d.get("IS_LEASE_HOLD_AR")),
        string_value(d.get("IS_OFFPLAN_EN")),
        string_value(d.get("IS_OFFPLAN_AR")),
        coerce_boolish_uint8(d.get("IS_REGISTERED")),
        string_value(d.get("PRE_REGISTRATION_NUMBER")),
        coerce_int(d.get("AREA_ID")),
        string_value(d.get("AREA_EN")),
        string_value(d.get("AREA_AR")),
        coerce_int(d.get("ZONE_ID")),
        string_value(d.get("ZONE_EN")),
        string_value(d.get("ZONE_AR")),
        coerce_int(d.get("MASTER_PROJECT_ID")),
        string_value(d.get("MASTER_PROJECT_EN")),
        string_value(d.get("MASTER_PROJECT_AR")),
        string_value(d.get("PROJECT_NUMBER")),
        string_value(d.get("PROJECT_EN")),
        string_value(d.get("PROJECT_AR")),
    )


load_release_to_clickhouse = build_open_data_bronze_loader(
    source_name=_SOURCE_NAME,
    column_names=_COLUMNS,
    row_builder=_row_tuple,
)
