from __future__ import annotations

import json
from typing import Any

from holocron.platform.bronze import (
    coerce_boolish_uint8,
    coerce_float,
    coerce_int,
    iso_datetime_or_default,
)
from holocron.platform.raw_files import string_value
from holocron.sources.dld_open_data_bronze import (
    build_open_data_bronze_loader,
    dld_envelope_tuple,
    dld_row_key,
)

_SOURCE_NAME = "dld_od_units"
_COLUMNS = (
    "row_key",
    "run_id",
    "scraped_at",
    "mode",
    "date_window_start",
    "date_window_end",
    "page_index",
    "row_index",
    "category",
    "endpoint",
    "raw_json",
    "property_id",
    "area_id",
    "zone_id",
    "area_en",
    "area_ar",
    "land_number",
    "land_sub_number",
    "building_number",
    "unit_number",
    "unit_balcony_area",
    "unit_parking_number",
    "parking_allocation_type",
    "parking_allocation_type_en",
    "parking_allocation_type_ar",
    "common_area",
    "actual_common_area",
    "floor",
    "rooms",
    "rooms_en",
    "rooms_ar",
    "actual_area",
    "property_type_id",
    "property_type_en",
    "property_type_ar",
    "property_sub_type_id",
    "prop_sub_type_en",
    "prop_sub_type_ar",
    "parent_property_id",
    "grandparent_property_id",
    "creation_date",
    "municipality_zip_code",
    "municipality_number",
    "parcel_id",
    "is_free_hold",
    "is_lease_hold",
    "is_registered",
    "pre_registration_number",
    "master_project_id",
    "master_project_en",
    "master_project_ar",
    "project_id",
    "project_en",
    "project_ar",
    "land_type_id",
    "land_type_en",
    "land_type_ar",
)


def _row_tuple(raw_row: dict[str, Any], *, fallback_run_id: str) -> tuple:
    row_key = dld_row_key(raw_row)
    raw_payload = raw_row.get("raw")
    d = raw_payload if isinstance(raw_payload, dict) else {}
    return (
        *dld_envelope_tuple(raw_row, row_key=row_key, fallback_run_id=fallback_run_id),
        string_value(raw_row.get("category")),
        string_value(raw_row.get("endpoint")),
        json.dumps(raw_payload, ensure_ascii=False) if raw_payload is not None else "",
        coerce_int(d.get("PROPERTY_ID")),
        coerce_int(d.get("AREA_ID")),
        coerce_int(d.get("ZONE_ID")),
        string_value(d.get("AREA_EN")),
        string_value(d.get("AREA_AR")),
        string_value(d.get("LAND_NUMBER")),
        string_value(d.get("LAND_SUB_NUMBER")),
        string_value(d.get("BUILDING_NUMBER")),
        string_value(d.get("UNIT_NUMBER")),
        coerce_float(d.get("UNIT_BALCONY_AREA")),
        string_value(d.get("UNIT_PARKING_NUMBER")),
        string_value(d.get("PARKING_ALLOCATION_TYPE")),
        string_value(d.get("PARKING_ALLOCATION_TYPE_EN")),
        string_value(d.get("PARKING_ALLOCATION_TYPE_AR")),
        coerce_float(d.get("COMMON_AREA")),
        coerce_float(d.get("ACTUAL_COMMON_AREA")),
        string_value(d.get("FLOOR")),
        string_value(d.get("ROOMS")),
        string_value(d.get("ROOMS_EN")),
        string_value(d.get("ROOMS_AR")),
        coerce_float(d.get("ACTUAL_AREA")),
        coerce_int(d.get("PROPERTY_TYPE_ID")),
        string_value(d.get("PROPERTY_TYPE_EN")),
        string_value(d.get("PROPERTY_TYPE_AR")),
        coerce_int(d.get("PROPERTY_SUB_TYPE_ID")),
        string_value(d.get("PROP_SUB_TYPE_EN") or d.get("PROPERTY_SUB_TYPE_EN")),
        string_value(d.get("PROP_SUB_TYPE_AR") or d.get("PROPERTY_SUB_TYPE_AR")),
        coerce_int(d.get("PARENT_PROPERTY_ID")),
        coerce_int(d.get("GRANDPARENT_PROPERTY_ID")),
        iso_datetime_or_default(d.get("CREATION_DATE")),
        string_value(d.get("MUNICIPALITY_ZIP_CODE") or d.get("MUNC_ZIP_CODE")),
        string_value(d.get("MUNICIPALITY_NUMBER") or d.get("MUNC_NUMBER")),
        string_value(d.get("PARCEL_ID")),
        coerce_boolish_uint8(d.get("IS_FREE_HOLD")),
        coerce_boolish_uint8(d.get("IS_LEASE_HOLD")),
        coerce_boolish_uint8(d.get("IS_REGISTERED")),
        string_value(d.get("PRE_REGISTRATION_NUMBER")),
        coerce_int(d.get("MASTER_PROJECT_ID")),
        string_value(d.get("MASTER_PROJECT_EN")),
        string_value(d.get("MASTER_PROJECT_AR")),
        coerce_int(d.get("PROJECT_ID")),
        string_value(d.get("PROJECT_EN") or d.get("PROJECT_NAME_EN")),
        string_value(d.get("PROJECT_AR") or d.get("PROJECT_NAME_AR")),
        coerce_int(d.get("LAND_TYPE_ID")),
        string_value(d.get("LAND_TYPE_EN")),
        string_value(d.get("LAND_TYPE_AR")),
    )


load_release_to_clickhouse = build_open_data_bronze_loader(
    source_name=_SOURCE_NAME,
    column_names=_COLUMNS,
    row_builder=_row_tuple,
)
